server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      password: LIUjun033453!
      username: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  scan:
    base-packages: com.zhuang.seata.order.rpc
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 nacos
    address: nacos://127.0.0.1:8848
  cloud:
    # 订阅的服务列表,以逗号分割
    subscribed-services: seata-account-service
  consumer:
    #启动时是否检查依赖的服务
    check: false

# 配置监控
management:
  endpoints:
    web:
      exposure:
        # spring boot actuator 监控所有端点
        include: '*'

seata:
  enabled: true
  application-id: seata-order
  tx-service-group: edu_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : SEATA_GROUP
      namespace:
      username: nacos
      password: nacos